UWEFlix_django/uweflix/urls.py
from django.urls import path
from uweflix import views
from uweflix.models import *



urlpatterns = [
    path("club_discount/", views.clubdiscount, name="club_discount"),
    path("account_modify/", views.account_modify, name="account_modify"),
    path("", views.viewings, name="home"),
    path("viewings/", views.viewings, name="viewings"),
    path("showings/<int:film>/", views.showings, name="showings_by_film"),
    path("add_film/", views.add_film, name="add_film"),
    path("login/", views.login, name="login"),
    path("topup/", views.topup, name="topup"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.registerPage, name="registerPage"),
    path("payment/<int:showing>/", views.payment, name="payment"),
    path("rep_payment/<int:showing>/", views.rep_payment, name="rep_payment"),
    path("pay_with_card/", views.pay_with_card, name="pay_with_card"),
    path("view_accounts/", views.view_accounts, name="view_accounts"),
    path("daily_transactions/", views.daily_transactions, name="daily_transactions"),
    path("customer_statements/", views.customer_statements, name="customer_statements"),
    path("thanks/", views.thanks, name="thanks"),
    path("user/", views.userpage, name="user-page"),
    path("add_club/", views.add_club, name="add_club"),
    path("add_rep/", views.add_rep, name="add_rep"),
    path("club_rep_home/", views.club_rep_home, name="club_rep_home"),
    path("cinema_manager_home/", views.cinema_manager_home, name="cinema_manager_home"),
    path("student_home/", views.student_home, name="student_home"),
    path("set_payment/", views.set_payment_details, name="set_payment"),
    path("am_home/", views.am_home, name="am_home"),
    path("settle_payments/", views.settle_payments, name="settle_payments"),
    path("review_students/<int:userID>", views.review_students, name="review_students"),
    path("rep_success/", views.rep_success, name="rep_success"),
    path("change_ticket_prices/", views.change_ticket_prices, name="change_ticket_prices"),
    path("view_order_history/", views.view_order_history, name="view_order_history"),
    path("request_cancellation/", views.request_cancellation, name="request_cancellation"),
    path("approve_cancellations/", views.approve_cancellation, name="approve_cancellations"),
    path("add_screen/", views.add_screen, name="add_screen"),
    path("add_showing/", views.add_showing, name="add_showing"),
]

UWEFlix_django/web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("uweflix.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

UWEFlix_django/uweflix/models.py
from email import charset
from pyexpat import model
from tokenize import String
from xml.dom.minidom import CharacterData
from django.db import models
from django.contrib.auth.models import *
from datetime import datetime as dt
import datetime

from django.forms import ValidationError

class User(AbstractUser):
    pass

class Customer(models.Model):  # Student accounts
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField('Date of birth')
    credit = models.FloatField(default=0.00)

class Transaction(models.Model):  # Database for storing all of the 'accounts' to be analysed by Account Manager
    customer = models.ForeignKey(Customer, blank=True, null=True, default=None, on_delete=models.SET_DEFAULT)  # User responsible for the transaction
    date = models.DateField()  # Date of transaction
    cost = models.FloatField()  # Cost of transaction
    is_settled = models.BooleanField()  # Whether the transaction has been paid
    request_to_cancel = models.BooleanField(default=False)
    def newTransaction(cust, cost, is_paid): #CREATE
        try:
            transaction = Transaction.objects.create(customer=cust, date=dt.today(), cost=cost, is_settled=is_paid)
            return transaction
        except:
            print("Transaction object could not be created.")

    def getTransaction(id): #READ
        try:
            transaction = Transaction.objects.get(id=id)
            return transaction
        except:
            print("No transaction exists with that transaction ID.")

    def updateTransaction(id, *transaction_data): #UPDATE
        try:
            for data_item in transaction_data:
                if isinstance(data_item, Customer):
                    Transaction.objects.filter(pk=id).update(customer=data_item)
                elif isinstance(data_item, datetime.date):
                    Transaction.objects.filter(pk=id).update(date=data_item)
                elif isinstance(data_item, float):
                    Transaction.objects.filter(pk=id).update(cost=data_item)
                elif isinstance(data_item, bool):
                    Transaction.objects.filter(pk=id).update(is_settled=data_item)
                else:
                    print(f"Data item {data_item} does not conform to any of the required input types." +
                    "\nThis value could not be updated.")
            return Transaction.objects.get(id=id)
        except:
            print("An error occurred when updating this object.")

    def deleteTransaction(id): #DELETE
        try:
            transaction = Transaction.objects.get(id=id)
            transaction.delete()
        except:
            print("This transaction does not exist, or had an issue being deleted.")

class Film(models.Model):
    title = models.CharField(max_length=100)
    age_rating = models.CharField(max_length=3)
    """Age Ratings:
        - U
        - PG
        - 12
        - 12A
        - 15
        - 18"""
    duration = models.CharField(max_length=3)
    # Store duration in minutes only (e.g. 120)
    trailer_desc = models.CharField(max_length=500)
    image = models.ImageField(default="placeholder.png")

    def newFilm (title, age_rating, duration, trailer_desc): #create
        try:
            film = Film.objects.create(title=title,age_rating=age_rating, duration=duration, trailer_desc=trailer_desc)
            return film
        except:
            print("Film could not be added")

    def getFilm(id): #read
        try:
            film = film.objects.get(id=id)
            return film
        except:
            print("Film could not be found")


    def removeFilm(id): #Delete
        try:
            film = Film.objects.get(id=id)
            if not Showing.objects.exists(film=film):
                film.delete()
            else:
                print ("Selected film has showings, couldn't be deleted")      
        except:
            print("Film could not be deleted, and may not exist")

    def updateFilm(id, fieldToEdit): #update
        try:
            for field in fieldToEdit:
                if isinstance(field, int):
                    Film.objects.filter(id=id).update(title=field)
                elif isinstance(field, bool):
                    Film.objects.filter(id=id).update(age_rating=field)
            return Film.objects.get(id=id)
        except:
            print("film could not be updated")

    def __str__(self):
        return self.title


class Screen(models.Model):
    capacity = models.IntegerField()
    apply_covid_restrictions =  models.BooleanField(null=True)

    def __str__(self):
        return "Screen " + str(self.id)

    def __str__(self):
        return "Screen " + str(self.id)

    def newScreen(seats, covidRestrictions): #Create
        try:
            screen = Screen.objects.create(capacity=seats, apply_covid_restrictions=covidRestrictions)
            return screen
        except:
            print("Screen cannot be created, perhaps you are missing some parameters?")

    def getScreen(id): #Read
        try:
            screen = Screen.objects.get(id=id)
            return screen
        except:
            print("Screen cannot be found, perhaps you have entered an incorrect id?")

    def updateScreen(id, fieldToEdit): #Update
        try:
            if isinstance(fieldToEdit, bool):
                Screen.objects.filter(id=id).update(apply_covid_restrictions=fieldToEdit)
            elif isinstance(fieldToEdit, (int, float)):
                Screen.objects.filter(id=id).update(capacity=fieldToEdit)
            return Screen.objects.get(id=id)
        except Exception as e:
            print("Screen cannot be found, perhaps you have entered an invalid field type?")
            print(e)

    def removeScreen(id): #Delete
        try:
            screen = Screen.objects.get(id=id)
            screen.delete()
        except:
            print("Screen cannot be found, perhaps you have entered an incorrect id?")

class Showing(models.Model):
    screen = models.ForeignKey(Screen, default=1, on_delete=models.CASCADE)
    film = models.ForeignKey(Film,on_delete=models.CASCADE)
    time = models.DateTimeField()
    remaining_tickets = models.IntegerField(default=150)  # NEEDS TO BE ASSIGNED TO THE SCREEN CAPACITY SOMEHOW!

    def newShowing(screen, film, time):#CREATE
        try:
            showing = Showing.objects.create(screen=screen, film=film, time=time, remaining_tickets=screen.capacity)
            if screen.apply_covid_restrictions == True:
                showing.remaining_tickets = showing.remaining_tickets / 2
                showing.save()
            return showing
        except:
            print("Showing object could not be created")

    def getShowing(id):#READ
        try:
            showing = Showing.objects.get(id=id)
            return showing
        except:
            print("No showinf exists with that showing ID.")

    def filmShowing(id, *showing_data): #UPDATE
        try:
            for data_item in showing_data:
                if isinstance(data_item, Screen):
                    Showing.objects.filter(pk=id).update(screen=data_item)
                elif isinstance(data_item, Film):
                    Showing.objects.filter(pk=id).update(film=data_item)
                elif isinstance(data_item, float):
                    Showing.objects.filter(pk=id).update(time=data_item)
                elif isinstance(data_item, int):
                    Showing.objects.filter(pk=id).update(remaining_tickets=data_item)
                elif isinstance(data_item, bool):
                    Showing.objects.filter(pk=id).update(apply_covid_restrictions=False)
                else:
                    print(f"Data item {data_item} does not confrom to any of the  required input types." +
                          "\nThis value could not be updated.")
            return Showing.objects.get(id=id)
        except:
            print("An error occurred when updating this object.")

    def deleteShowing(id): #DELETE
        try:
            showing = Showing.objects.get(id=id)
            showing.delete()
        except:
            print("This film Showing has Successfully been deleted.")


class Ticket(models.Model):  # Individual ticket booking database
    transaction = models.ForeignKey(Transaction, default=1, on_delete=models.SET_DEFAULT)
    showing = models.ForeignKey(Showing, default=1, on_delete=models.SET_DEFAULT)  # Screen the booking is being viewed at
    ticket_type = models.CharField(max_length=7)

    def newTicket(trans, show, type): #Create
        try:
            ticket = Ticket.objects.create(transaction=trans, showing=show, ticket_type=type)
            return ticket
        except:
            print("Ticket cannot be created, perhaps you are missing a parameter?")

    def getTicket(id): #Read
        try:
            ticket = Ticket.objects.get(id=id)
            return ticket
        except:
            print("Ticket cannot be found, perhaps you have entered an incorrect id?")

    def updateTicket(id, fieldToEdit): #Update
        try:
            for field in fieldToEdit:
                if isinstance(field, Transaction):
                    Ticket.objects.filter(id=id).update(transaction=field)
                elif isinstance(field, Showing):
                    Ticket.objects.filter(id=id).update(showing=field)
                elif isinstance(field, String):
                    Ticket.objects.filter(id=id).update(ticket_type=field)
            return Ticket.objects.get(id=id)
        except:
            print("Ticket cannot be updated, perhaps you have entered an invalid field type?")

    def removeTicket(id): #Delete
        try:
            ticket = Ticket.objects.get(id=id)
            ticket.delete()
        except:
            print("Ticket cannot be found, perhaps you have entered an invalid id?")


class Club(models.Model):
    name = models.CharField(max_length=100)
    #Address details

UWEFlix_django/uweflix/templates/uweflix/account_modify.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Account Modify
{% endblock %}
{% block content %}
<h1>Account Modify</h1>
<hr/>
<script>
    $( function() {
      $( "#id_dob" ).datepicker({
          dateFormat: "yy-mm-dd"
      });
    } );
</script>

<form method='POST' class="form-area" action="" autocomplete="off">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-warning"name = select_user>Select</button>
    <hr/>

    <p>Current Password: {{ form.password1 }}</p>
    <p>First Name: {{ form.first_name }}</p>
    <p>Last Name: {{ form.last_name }}</p>
    <p>Username: {{ form.username }}</p>
    <p>Email: {{ form.email }}</p>
    <p>New Password: {{ form.password2 }}</p>
    <p>Date of Birth: {{ customer_form.dob }}</p>
    <br/>



</form>
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/add_account.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
<form method="post" class="form-group">

    {% csrf_token %} {{ form }}

    <button type="submit" class="btn btn-success">Add Rep</button>

    </form>
{% endblock %}
{% block content %}
<h2>Welcome Add Rep Here<h2>
    <form method="post" class="form-group">

        {% csrf_token %} {{ form }}

        <button type="submit" class="btn btn-success">Add Rep</button>

        </form>
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/add_rep.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Add Rep
{% endblock %}
{% block content %}
<h1>Add Club Rep</h1>
<script>
    $( function() {
      $( "#id_dob" ).datepicker({
          dateFormat: "yy-mm-dd",
          changeMonth: true,
          changeYear: true
      });
    } );
</script>
    <form method="post" class="form-area" autocomplete="off">
        {% if club_rep %}
        <div class="success-string">Success: your new Club Rep account has been created.<br/>Username: {{club_rep.user.username}}</div>
        {% endif %}
        {% csrf_token %}
        <hr/>
        <div class="form-group">
        {{ userform.as_p }}
        </div>
        <br/>
        <br/>
        <hr/>
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <br/>
        <br/>
        <hr/>
        <div class="form-group">
            <button id="confirm-btn" type="submit" class="btn btn-warning">Add Rep</button>
        </div>
        </form>
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/add_screen.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
    Add a screen
{% endblock %}
{% block content %}
<h1>Add Screen</h1>

<style>
    .submit-button {
        margin: 10px 10px 10px 10px;
    } 
</style>

<form method="post" class="form-area" autocomplete="off">
    <hr>
    {% csrf_token %}
    <div class="form-group">
    {{ form.as_p }}
    </div>
    <br/>
    <br/>
    <hr>
    <div class="form-group">
    <button id="confirm-btn" type="submit" class="btn btn-warning">Add Screen</button>
    </div>
</form>
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/change_ticket_prices.html
{% extends "uweflix/layout.html" %}
{% block title %}
Change Ticket Prices
{% endblock %}
{% block content %}
<h1>Change Ticket Prices</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-area">
        <hr/>
        <div class="form-group">
        {{form.as_p}}
        </div>
        <br/>
        <br/>
        <hr/>
    </div>
    <div class="form-group">
        <input id="confirm-btn" class="btn btn-warning" type="submit" value="Change">
    </div>
</form>
{% if confirm %}
{{ confirm }}
{% endif %}
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/error.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Error
{% endblock %}
{% block content %}
<h1>Error</h1>
{{ error }}
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/layout.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'uweflix/site.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <script type="text/javascript" src="{{ STATIC_URL }} /static/js/jquery-3.6.0.js"></script>
    <script type="text/javascript" language="javascript" src="http://code.jquery.com/jquery-latest.js"></script> 
    <script type="text/javascript" src="{{ STATIC_URL }} https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="{{ STATIC_URL }} /static/js/rango-jquery.js"></script>
</head>

<body>
<!-- <div class="navbar">
    <a href="{% url 'home' %}" class="navbar-brand">Home</a>
    <a href="{% url 'viewings' %}" class="navbar-item">Viewings</a>
</div> -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'viewings' %}">
            <img src="{% static 'uweflix/images/logo.png' %}" height="50" width="140" style="margin-left: 20px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                {% if request.session.user_group == "Club Rep"%}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'settle_payments' %}">Settle Payments</a>
                    </li>
                {% elif request.session.user_group == "Cinema Manager" %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_film' %}">Manage Films</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_screen' %}">Add Screen</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_showing' %}">Add Showing</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'change_ticket_prices' %}">Change Ticket Prices</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_club' %}">Add Club</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'add_rep' %}">Add Club Rep</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'approve_cancellations' %}">Cancellations</a>
                </li>
                {% elif request.session.user_group == "Account Manager" %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'daily_transactions' %}">Transactions</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'customer_statements' %}">Customer Statements</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'set_payment' %}">Set Payment Details</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'club_discount' %}">Club Discount</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'account_modify' %}">Amend Account</a>
                </li>                                
                {% endif %}
            </ul>
            {% if request.session.user_id is None %}
            <div class="topnav-right">
                <a class="nav-link" href="{% url 'registerPage' %}">Register</a>
            </div>
            <div class="form-inline my-2 my-lg-0">
                <a href="{% url 'login' %}"class="btn btn-warning">Login</a>
            </div>
            {% else %}
                {% if request.session.user_group == "Student" or request.session.user_group == "Club Rep" %}
                <div class="topnav-right">
                    <a class="nav-link" href="{% url 'topup' %}">£{{ request.session.credit|floatformat:2 }}</a>
                </div>
                {% endif %}
                <div class="topnav-right">
                    {% if request.session.user_group == "Account Manager" %}
                    <a class="navbar-brand" href="{% url 'am_home' %}">Settings</a>
                    {% elif request.session.user_group == "Cinema Manager" %}
                    <a class="navbar-brand" href="{% url 'cinema_manager_home' %}">Settings</a>
                    {% elif request.session.user_group == "Club Rep" %}
                    <a class="navbar-brand" href="{% url 'club_rep_home' %}">Settings</a>
                    {% elif request.session.user_group == "Student" %}
                    <a class="navbar-brand" href="{% url 'student_home' %}">Settings</a>
                    {% endif %}
                </div>
            <div class="form-inline my-2 my-lg-0">
                <a href="{% url 'logout' %}"class="btn btn-warning">Logout</a>
            </div>
            {% endif %}
        </div>
    </nav>
    <div class="flex-wrapper">
    <div class="body-content">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <br/>
    <div class="footer">
        <footer class="navbar navbar-expand-lg navbar-dark bg-dark">
            <hr/>
            <div class="form-area" style="margin-left: 20px;">
                <p class="navbar-brand">Options:</p>
                <p style="color: lightgray;">Colour-blind friendly mode:
                <label class="switch">
                    <input type="checkbox" id="colourBlindBox" onclick="setColourBlindOptions()">
                    <span class="slider round"></span>
                </label>
                </p>
                <p style="color: lightgray;">Font size: 
                    <input type="button" id="increase" class="btn btn-success" value=" + ">
                    <input type="button" id="resetMe" class="btn btn-secondary" value=" = ">
                    <input type="button" id="decrease" class="btn btn-danger" value=" - "/></p>
                <p class="navbar-brand">© UWEFlix 2022</p>
            </div>
        </footer>
    </div>
</div>
    <script>
        var prevColour = document.body.style.background;
        var prevText = document.body.style.color;
        var prevTitleH1 = document.getElementsByTagName("h1")[0].style.color;
        var prevTitleH2 = document.getElementsByTagName("h2")[0].style.color;
        var prevTitleH3 = document.getElementsByTagName("h3")[0].style.color;
        var prevTitleH4 = document.getElementsByTagName("h4")[0].style.color;
        var prevTitleH5 = document.getElementsByTagName("h5")[0].style.color;
        var prevTitleH6 = document.getElementsByTagName("h6")[0].style.color;
        var titleColours = ["white", "white", "white", "white", "white", "white"];
        function setColourBlindOptions() {
            var h1Tags = document.getElementsByTagName("h1");
            var h2Tags = document.getElementsByTagName("h2");
            var h3Tags = document.getElementsByTagName("h3");
            var h4Tags = document.getElementsByTagName("h4");
            var h5Tags = document.getElementsByTagName("h5");
            var h6Tags = document.getElementsByTagName("h6");
            var titleTags = [h1Tags, h2Tags, h3Tags, h4Tags, h5Tags, h6Tags];
            var checkbox = document.getElementById("colourBlindBox");
            if (checkbox.checked == true) {
                document.body.style.background = "blue";
                document.body.style.color = "orange";
                for(var i = 0; i < titleTags.length; i++) {
                    for(var j = 0; j < titleTags[i].length; j++) {
                        titleTags[i][j].style.color = "orange";
                    }
                }
            } else {
                document.body.style.background = prevColour;
                document.body.style.color = prevText;
                for(var i = 0; i < titleTags.length; i++) {
                    for(var j = 0; j < titleTags[i].length; j++) {
                        titleTags[i][j].style.color = "#4D4D4D";
                    }
                }
            }
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
        var originalSize = $('div').css('font-size');
        // reset
        $("#resetMe").click(function(){
        $('div').css('font-size', originalSize);
        });
        
        // Increase Font Size
        $("#increase").click(function(){
        var currentSize = $('div').css('font-size');
        var currentSize = parseFloat(currentSize)*1.2;
        $('div').css('font-size', currentSize);
        return false;
        });

        // Decrease Font Size
        $("#decrease").click(function(){
            var currentFontSize = $('div').css('font-size');
            var currentSize = $('div').css('font-size');
            var currentSize = parseFloat(currentSize)*0.8;
            $('div').css('font-size', currentSize);
            return false;
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

UWEFlix_django/uweflix/templates/uweflix/login.html
{% extends "uweflix/layout.html" %}
{% block title %}
Login
{% endblock %}
{% block content %}

<style>
    h1 {
        text-align: center;
        margin: 10px;
    }


    div.form {
        display: block;
        text-align: center;
    }

    form {
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
    }

    .inputFields {
        width: 200px;
        padding: 10px;
        margin: 10px 0; 
        border-radius: 12px;
        box-shadow: 0 0 5px 4px rgba(211,211,211,0.8);
    }
    .submitButton {
        width: 200px;
        padding: 5px;
        margin: 25px 0; 
        background-color: #ffc107;
        color: black;
        font-weight: bold;
        box-shadow: 0 0 1px 1px rgba(0,0,0,0.8);
    }

    .extraHeight {
        height: 150px;
    }

</style>

<h1>Log in to UWEFlix</h1>
<div class = "form">
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username:</label><br>
        <input type = "text", name = "username", class="inputFields", placeholder="Enter Username"><br>
        <label for="password">Password:</label><br>
        <input type = "password", name = "password", class="inputFields", placeholder="Enter Password"><br>
        <input type="submit" value="Login", class="submitButton">
    </form>
</div>

{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/register_cr.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Register a Club Rep
{% endblock %}
{% block content %}
<h2>Register a Club Rep</h2>
<form method='POST' action="">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ cr_form.as_p }}
    <input type="submit" name="Create Club Rep">
</form>
{% endblock %}

UWEFlix_django/uweflix/templates/uweflix/set_payment.html
{% extends "uweflix/layout.html" %}
{% load static %}
{% block title %}
Set Payment Details
{% endblock %}
{% block content %}
<h1>Set Club Payment Details</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-area">
        <div class="alert-error">
            {{ form.non_field_errors }}
        </div>
        <div class="form-group">
            <p>Club: {{ form.club }}</p>
        </div>
        <hr/>
        <div class="form-group">
            <p>Card Number: {{ form.card_number }}</p>
        </div>
        <div class="form-group">
                <p><div class="expiry-label">Expiry Date: </div><div class="expiry-section">{{ form.expiry_month }} / {{ form.expiry_year }}</div></p>
        </div>
        <hr/>
        <div class="form-group">
            <input id="set-payment-btn" class="btn btn-warning" type="submit" value="Confirm">
        </div>
    </div>
</form>
{% endblock %}